default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  encoding: unicode
  database: togglelocaldb

test:
  <<: *default
  encoding: unicode
  database: togglelocaldb

production:
  <<: *default
  encoding: utf8
  username: 'toggledbadmin'
  password: 'jhUHXNC5NujYBHyqTnnU'
  host: 'soundtoggle-pgdb.cdrvqu0gaiwk.us-east-1.rds.amazonaws.com'
  port: 5432
  database: 'soundtoggledb'
