default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  encoding: utf8
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
  port: 5432
  database: <%= Rails.application.credentials.dig(:db, :database) %>

development:
  <<: *default
  database: 'soundtogglelocaldb'